name: app_power_house
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.5.1
  fl_chart: ^0.70.2
  shared_preferences: ^2.0.15
  flutter_background_service: ^5.1.0
  sqflite: ^2.0.2
  path_provider: ^2.0.11
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
